Dev
recski/tuw-nlp pull request #31
Opened 2021-05-04 07:17 UTC by adaamko

@recski  added expand and substitute functionality to TextTo4lang, also introduced a Fourlang class

2021-05-11 05:09 UTC, recski requested changes

2021-05-12 08:28 UTC, adaamko commented on tuw_nlp/grammar/text_to_4lang.py
> +                        sen = self.nlp(definition).sentences[0]
Should it be really cached? It is essentially just a dictionary lookup and the rest is already cached (ud parsing, UD_FL conversion)

2021-05-12 08:49 UTC, recski commented on tuw_nlp/grammar/text_to_4lang.py
> +                        sen = self.nlp(definition).sentences[0]
@adaamko you are right, sorry, if all steps are cached then there's no need. (But for that the self.nlp should also be a CachedPipeline, right?)

2021-05-12 08:51 UTC, recski approved these changes

2021-05-12 08:51 UTC, merged

2021-05-12 09:20 UTC, adaamko commented on tuw_nlp/grammar/text_to_4lang.py
> +                        sen = self.nlp(definition).sentences[0]
@recski yes self.nlp should be CachedPipeline, but we initialize it like that in line 28:
`        self.nlp = CachedStanzaPipeline(nlp, nlp_cache)
`

2021-05-12 09:26 UTC, recski commented on tuw_nlp/grammar/text_to_4lang.py
> +                        sen = self.nlp(definition).sentences[0]
excellent, thanks!